#!/bin/sh
MAKE="256"

## Set compiler location
echo Setting compiler location...
export ARCH=arm
export CROSS_COMPILE=/home/sultan/Downloads/android-toolchain-eabi/bin/arm-eabi-

## Build Sultan kernel
make -j$MAKE ARCH=arm
sleep 1
echo Copying Modules
sleep 1
cp -a $(find . -name *.ko -print |grep -v initramfs) /home/sultan/Documents/modules-jb


