#!/bin/sh
MAKE="200"

## Set compiler location
echo Setting compiler location...
export ARCH=arm
export CROSS_COMPILE=/home/sultan/Downloads/arm-cortex_a8-linux-gnueabi-linaro_4.8-2013.04/bin/arm-cortex_a8-linux-gnueabi-

## Build Sultan kernel
make -j$MAKE ARCH=arm
sleep 1
echo Copying Modules
sleep 1
cp -a $(find . -name *.ko -print |grep -v initramfs) /home/sultan/Documents/modules-jb


